import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'bg';

const en = {
    // ── Common ────────────────────────────────────────────────────────────────
    loading: 'Loading...',
    cancel: 'Cancel',
    save: 'Save',
    admin: 'Admin',
    user: 'User',

    // ── Language switcher ─────────────────────────────────────────────────────
    langEn: 'EN',
    langBg: 'BG',

    // ── Landing Page ──────────────────────────────────────────────────────────
    landingBadge: 'Document Intelligence Platform',
    landingTagline: 'Your complete dashboard for document processing usage, billing, and support.',
    poweredBy: 'Powered by AI Assist BG',
    featureRealTime: 'Real-time usage monitoring',
    featureMultiTenant: 'Multi-tenant organization support',
    featureBilling: 'Integrated billing & support',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    signInSubtitle: 'Sign in to access your dashboard',
    signUpSubtitle: 'Sign up to start tracking your usage',
    yourName: 'Your Name',
    organizationName: 'Organization Name',
    email: 'Email',
    password: 'Password',
    namePlaceholder: 'John Doe',
    orgPlaceholder: 'Acme Corp',
    emailPlaceholder: 'you@company.com',
    processing: 'Processing...',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    createNow: 'Create one now',
    signInInstead: 'Sign in instead',
    registrationSuccess: 'Registration successful! Please log in.',
    errorOccurred: 'An error occurred',

    // ── Layout ────────────────────────────────────────────────────────────────
    selectTenant: 'Select Tenant',
    logout: 'Logout',
    navUsage: 'Usage',
    navBilling: 'Billing',
    navSupport: 'Support',
    navUsers: 'Users',
    navImport: 'Import file',

    // Usage limit banner
    bannerTitle: "You've reached your current usage limit, and your agent has been temporarily paused.",
    bannerBody: 'To resume your agent, please either:',
    bannerOption1: 'Purchase additional pages/rows on the Billing page, or',
    bannerOption2: 'Upgrade your subscription plan.',
    bannerFooter: 'Once your limit is increased, your agent will automatically resume.',

    // ── Dashboard ─────────────────────────────────────────────────────────────
    usageDashboard: 'Usage Dashboard',
    usageDashboardSubtitle: 'Track your document processing usage across all platforms',
    export: 'Export',
    refreshSync: 'Refresh / Sync',
    wait: 'Wait...',
    settings: 'Settings',
    last7days: 'Last 7 days',
    last30days: 'Last 30 days',
    custom: 'Custom',
    daysPlaceholder: 'Days (1–30)',
    apply: 'Apply',
    customDaysError1: 'Please enter a number between 1 and 30.',
    customDaysError2: 'Maximum allowed is 30 days.',
    infrastructureUsage: 'Infrastructure Usage',
    documentUsage: 'Document Usage',
    scenarios: 'Scenarios:',
    paused: 'Paused',
    running: 'Running',
    working: 'Working…',
    pauseScenarios: 'Pause Scenarios',
    resumeScenarios: 'Resume Scenarios',
    resetting: 'Resetting…',
    resetPagesRows: 'Reset Pages & Rows',
    credits: 'credits',
    events: 'events',
    tokens: 'tokens',
    pages: 'pages',
    rows: 'rows',
    operations: 'operations',
    totalCost: 'Total Cost',
    pdfPagesProcessed: 'PDF Pages Processed',
    excelRowsExtracted: 'Excel Rows Extracted',
    usageOverTime: 'Usage Over Time',
    monthlyUsageHistory: 'Monthly Usage History',
    noMonthlyHistory: 'No monthly history yet. History is recorded automatically when you reset usage.',
    month: 'Month',
    pdfPages: 'PDF Pages',
    excelRows: 'Excel Rows',
    current: 'Current',
    agentPaused: 'Agent Paused',
    agentPausedDesc: '— usage limit reached. Go to the Billing tab to resume or purchase add-ons.',
    pdfPagesSpent: 'PDF Pages Spent',
    excelRowsUsed: 'Excel Rows Used',
    pdfPagesBillingCycle: 'PDF Pages processed in the current billing cycle',
    excelRowsBillingCycle: 'Excel Rows extracted in the current billing cycle',
    extraPdfPages: 'Extra PDF pages (add-on):',
    extraExcelRows: 'Extra Excel rows (add-on):',
    documentUsageOverTime: 'Document Usage Over Time',
    integrationSettings: 'Integration Settings',
    apiKey: 'API Key',
    organizationId: 'Organization ID',
    folderId: 'Folder ID (optional - filters synced scenarios)',
    endpoint: 'Endpoint',
    enterMakeApiKey: 'Enter Make.com API Key',
    enterAzureApiKey: 'Enter Azure API Key',
    testingConn: 'Testing...',
    testConnection: 'Test Connection',
    testAzureConnection: 'Test Azure Connection',
    saveSettings: 'Save Settings',
    loadingUsage: 'Loading usage data...',
    lastNDays: (n: number) => `Last ${n} days`,
    totalEventsDesc: (count: number, days: number) => `${count} total events across all sources in last ${days} days`,
    resetConfirm: 'This will permanently delete ALL pages and rows usage data, resetting both counters to 0 everywhere.\n\nMake.com, Azure, and OpenAI usage data will NOT be affected.\n\nContinue?',
    syncFailed: 'Failed to sync data',
    resetFailed: 'Reset failed. Make sure you have admin privileges.',
    settingsSaved: 'Settings saved successfully!',
    settingsFailed: 'Failed to save settings.',
    pauseErrorServer: 'Pause failed: could not reach the server. Check your Make.com API key.',
    pauseErrorAll: (count: number) => `Pause failed: all ${count} scenario(s) returned an error from Make.com. Check the server logs for details.`,
    resumeErrorServer: 'Resume failed: could not reach the server. Check your Make.com API key.',
    resumeErrorAll: (count: number) => `Resume failed: all ${count} scenario(s) returned an error from Make.com. Check the server logs for details.`,

    // ── Billing ───────────────────────────────────────────────────────────────
    billingTitle: 'Billing & Subscription',
    billingSubtitle: 'Manage your subscription and monitor usage limits',
    agentPausedBilling: 'Your Agent has been paused',
    agentPausedBillingDesc: '— you have reached your usage limit for this billing period.',
    autoResume: (date: string) => ` Your scenarios will auto-resume on ${date} when the new period starts.`,
    purchaseToResume: ' Purchase additional pages or rows below to resume, or upgrade your subscription.',
    currentPeriodUsage: 'Current Period Usage',
    professionalPlan: 'Professional Plan',
    enterprisePlan: 'Enterprise Plan',
    resetsOn: (date: string) => `Resets on ${date}`,
    pdfPagesUsed: 'PDF Pages Used',
    excelRowsUsed2: 'Excel Rows Used',
    extraPdfPagesAddon: 'Extra PDF Pages (add-on)',
    extraExcelRowsAddon: 'Extra Excel Rows (add-on)',
    subscriptionPlans: 'Subscription Plans',
    mostPopular: 'Most Popular',
    currentPlan: 'Current Plan',
    perMonth: '/month',
    currentlyChosen: 'Currently chosen plan',
    downgradeTo: (name: string) => `Downgrade to ${name}`,
    upgradeTo: (name: string) => `Upgrade to ${name}`,
    subscribeTo: (price: string) => `Subscribe — ${price}/mo`,
    downgradeNotice: 'If you want to downgrade or cancel your subscription please submit a ticket through the Support tab.',
    addons: 'Add-ons',
    addonsDesc: 'Purchase additional capacity as a one-time payment for the current billing period. Scenarios are automatically resumed after a successful payment (requires Stripe webhook configuration).',
    addlPdfDesc: 'Additional PDF page processing capacity',
    addlRowsDesc: 'Additional Excel row processing capacity',
    oneTimePayment: 'One-time payment',
    purchaseItem: (label: string) => `Purchase ${label}`,
    testPayments: 'Test Payments',
    adminOnly: 'Admin Only',
    testPaymentsDesc: 'Stripe test-mode links — use card',
    testPaymentsDesc2: ', any future date, any CVC. These run through the same webhook flow as live payments so you can verify the full integration end-to-end.',
    openTestCheckout: 'Open Test Checkout',
    subscriptionBadge: 'Subscription',
    addonBadge: 'Add-on',

    // ── Tickets ───────────────────────────────────────────────────────────────
    support: 'Support',
    supportSubtitle: 'Get help from our support team',
    issueSystemNotWorking: 'System not working',
    issueFilesIssues: 'Files issues - missing files, incorrect data, etc.',
    issueGeneralSupport: 'General support',
    issueDowngradeCancel: 'Downgrade/Cancel subscription',
    selectOption: '— Select an option —',
    chooseAssistance: 'Please choose what you need assistance with',
    description: 'Description',
    optional: '(optional)',
    descPlaceholder: 'Describe your issue in more detail...',
    submitting: 'Submitting...',
    submitRequest: 'Submit Request',
    requestSubmitted: 'Request Submitted!',
    requestSubmittedDesc: 'Our support team will review your request and get back to you shortly.',
    submitAnother: 'Submit Another Request',
    submitFailed: 'Failed to send your request. Please try again.',

    // ── Users ─────────────────────────────────────────────────────────────────
    usersManagement: 'Users Management',
    createUser: 'Create User',
    name: 'Name',
    role: 'Role',
    actions: 'Actions',
    noUsersFound: 'No users found',
    loadingUsers: 'Loading users...',
    fullName: 'Full Name',
    emailRequired: 'Email *',
    passwordRequired: 'Password *',
    roleRequired: 'Role *',
    namePlaceholderUser: 'John Doe',
    minChars: 'Minimum 8 characters',
    creating: 'Creating...',
    removeUser: 'Remove user',
    removeConfirm: (email: string) => `Remove ${email} from this tenant?`,
    removeUserFailed: 'Failed to remove user',
    createUserFailed: 'Failed to create user',
    changePassword: 'Change Password',
    newPassword: 'New Password *',
    savingPassword: 'Saving...',
    changePasswordFailed: 'Failed to change password',
    passwordChanged: 'Password changed successfully',
    tabUsers: 'Users',
    tabImport: 'Import',
    uploadFile: 'Upload File',
    uploading: 'Uploading...',
    uploadSuccess: 'File uploaded successfully',
    uploadFailed: 'Failed to upload file',
    dragDropFile: 'Drag & drop a file here, or click to select',
    noFileSelected: 'No file selected',
    selectFile: 'Select File',
    download: 'Download',
};

const bg: typeof en = {
    // ── Common ────────────────────────────────────────────────────────────────
    loading: 'Зареждане...',
    cancel: 'Отказ',
    save: 'Запази',
    admin: 'Администратор',
    user: 'Потребител',

    // ── Language switcher ─────────────────────────────────────────────────────
    langEn: 'EN',
    langBg: 'BG',

    // ── Landing Page ──────────────────────────────────────────────────────────
    landingBadge: 'Платформа за интелигентна обработка на документи',
    landingTagline: 'Вашето пълно табло за употреба при обработка на документи, фактуриране и поддръжка.',
    poweredBy: 'Powered by AI Assist BG',
    featureRealTime: 'Мониторинг на употребата в реално време',
    featureMultiTenant: 'Поддръжка за множество организации',
    featureBilling: 'Интегрирано фактуриране и поддръжка',
    welcomeBack: 'Добре дошли отново',
    createAccount: 'Създаване на акаунт',
    signInSubtitle: 'Влезте, за да достъпите таблото си',
    signUpSubtitle: 'Регистрирайте се, за да проследявате употребата си',
    yourName: 'Вашето Ime',
    organizationName: 'Наименование на организацията',
    email: 'Имейл',
    password: 'Парола',
    namePlaceholder: 'Иван Иванов',
    orgPlaceholder: 'Примерна ООД',
    emailPlaceholder: 'вие@компания.com',
    processing: 'Обработване...',
    signIn: 'Вход',
    noAccount: 'Нямате акаунт?',
    haveAccount: 'Вече имате акаунт?',
    createNow: 'Създайте го сега',
    signInInstead: 'Влезте вместо това',
    registrationSuccess: 'Регистрацията е успешна! Моля, влезте.',
    errorOccurred: 'Възникна грешка',

    // ── Layout ────────────────────────────────────────────────────────────────
    selectTenant: 'Изберете организация',
    logout: 'Изход',
    navUsage: 'Употреба',
    navBilling: 'Фактуриране',
    navSupport: 'Поддръжка',
    navUsers: 'Потребители',
    navImport: 'Импорт на файл',

    // Usage limit banner
    bannerTitle: 'Достигнахте текущия лимит за употреба и вашият агент беше временно спрян.',
    bannerBody: 'За да стартирате агента отново, моля:',
    bannerOption1: 'Закупете допълнителни страници/редове от страницата за фактуриране, или',
    bannerOption2: 'Надстройте абонаментния си план.',
    bannerFooter: 'Веднага след увеличаване на лимита, агентът ви ще се стартира автоматично.',

    // ── Dashboard ─────────────────────────────────────────────────────────────
    usageDashboard: 'Табло за употреба',
    usageDashboardSubtitle: 'Проследявайте употребата при обработка на документи на всички платформи',
    export: 'Експортиране',
    refreshSync: 'Опресняване / Синхронизиране',
    wait: 'Изчакайте...',
    settings: 'Настройки',
    last7days: 'Последните 7 дни',
    last30days: 'Последните 30 дни',
    custom: 'Потребителски',
    daysPlaceholder: 'Дни (1–30)',
    apply: 'Приложи',
    customDaysError1: 'Моля, въведете число между 1 и 30.',
    customDaysError2: 'Максималният разрешен период е 30 дни.',
    infrastructureUsage: 'Инфраструктурна употреба',
    documentUsage: 'Употреба на документи',
    scenarios: 'Сценарии:',
    paused: 'Спрени',
    running: 'Активни',
    working: 'Изпълнява се…',
    pauseScenarios: 'Спиране на сценарии',
    resumeScenarios: 'Стартиране на сценарии',
    resetting: 'Нулиране…',
    resetPagesRows: 'Нулиране на страници и редове',
    credits: 'кредити',
    events: 'събития',
    tokens: 'токени',
    pages: 'страници',
    rows: 'редове',
    operations: 'операции',
    totalCost: 'Обща цена',
    pdfPagesProcessed: 'Обработени PDF Страници',
    excelRowsExtracted: 'Извлечени Excel Редове',
    usageOverTime: 'Употреба с течение на времето',
    monthlyUsageHistory: 'Месечна история на употребата',
    noMonthlyHistory: 'Все още няма месечна история. Историята се записва автоматично при нулиране на употребата.',
    month: 'Месец',
    pdfPages: 'PDF Страници',
    excelRows: 'Excel Редове',
    current: 'Текущ',
    agentPaused: 'Агентът е спрян',
    agentPausedDesc: '— достигнат е лимитът за употреба. Отидете в раздела Фактуриране, за да стартирате отново или закупите добавки.',
    pdfPagesSpent: 'Изразходвани PDF Страници',
    excelRowsUsed: 'Използвани Excel Редове',
    pdfPagesBillingCycle: 'PDF Страници, обработени в текущия период на фактуриране',
    excelRowsBillingCycle: 'Excel Редове, извлечени в текущия период на фактуриране',
    extraPdfPages: 'Допълнителни PDF страници (добавка):',
    extraExcelRows: 'Допълнителни Excel редове (добавка):',
    documentUsageOverTime: 'Употреба на документи с течение на времето',
    integrationSettings: 'Настройки за интеграция',
    apiKey: 'API Ключ',
    organizationId: 'ID на организацията',
    folderId: 'ID на папка (опционално - филтрира синхронизираните сценарии)',
    endpoint: 'Крайна точка',
    enterMakeApiKey: 'Въведете API ключ за Make.com',
    enterAzureApiKey: 'Въведете API ключ за Azure',
    testingConn: 'Тестване...',
    testConnection: 'Тест на връзката',
    testAzureConnection: 'Тест на Azure връзката',
    saveSettings: 'Запазване на настройките',
    loadingUsage: 'Зареждане на данните за употребата...',
    lastNDays: (n: number) => `Последните ${n} дни`,
    totalEventsDesc: (count: number, days: number) => `${count} общо събития от всички източници за последните ${days} дни`,
    resetConfirm: 'Това ще изтрие окончателно ВСИЧКИ данни за употреба на страници и редове, нулирайки и двата брояча до 0 навсякъде.\n\nДанните за употреба на Make.com, Azure и OpenAI НЯМА да бъдат засегнати.\n\nПродължете?',
    syncFailed: 'Неуспешно синхронизиране на данни',
    resetFailed: 'Неуспешно нулиране. Уверете се, че имате администраторски права.',
    settingsSaved: 'Настройките са запазени успешно!',
    settingsFailed: 'Неуспешно запазване на настройките.',
    pauseErrorServer: 'Неуспешно спиране: не може да се свърже със сървъра. Проверете API ключа за Make.com.',
    pauseErrorAll: (count: number) => `Неуспешно спиране: всички ${count} сценарий(и) върнаха грешка от Make.com. Проверете сървърните логове за подробности.`,
    resumeErrorServer: 'Неуспешно стартиране: не може да се свърже със сървъра. Проверете API ключа за Make.com.',
    resumeErrorAll: (count: number) => `Неуспешно стартиране: всички ${count} сценарий(и) върнаха грешка от Make.com. Проверете сървърните логове за подробности.`,

    // ── Billing ───────────────────────────────────────────────────────────────
    billingTitle: 'Фактуриране и абонамент',
    billingSubtitle: 'Управлявайте абонамента си и следете лимитите за употреба',
    agentPausedBilling: 'Вашият агент е спрян',
    agentPausedBillingDesc: '— достигнали сте лимита за употреба за текущия период на фактуриране.',
    autoResume: (date: string) => ` Сценариите ви ще се стартират автоматично на ${date}, когато започне новият период.`,
    purchaseToResume: ' Закупете допълнителни страници или редове по-долу, за да стартирате, или надстройте абонамента си.',
    currentPeriodUsage: 'Употреба за текущия период',
    professionalPlan: 'Професионален план',
    enterprisePlan: 'Enterprise план',
    resetsOn: (date: string) => `Нулира се на ${date}`,
    pdfPagesUsed: 'Използвани PDF Страници',
    excelRowsUsed2: 'Използвани Excel Редове',
    extraPdfPagesAddon: 'Допълнителни PDF Страници (добавка)',
    extraExcelRowsAddon: 'Допълнителни Excel Редове (добавка)',
    subscriptionPlans: 'Абонаментни планове',
    mostPopular: 'Най-популярен',
    currentPlan: 'Текущ план',
    perMonth: '/месец',
    currentlyChosen: 'Текущо избран план',
    downgradeTo: (name: string) => `Преминаване към ${name}`,
    upgradeTo: (name: string) => `Надстройване към ${name}`,
    subscribeTo: (price: string) => `Абонирайте се — ${price}/мес`,
    downgradeNotice: 'Ако искате да понижите или отмените абонамента си, моля подайте заявка чрез раздела Поддръжка.',
    addons: 'Добавки',
    addonsDesc: 'Закупете допълнителен капацитет чрез еднократно плащане за текущия период на фактуриране. Сценариите се стартират автоматично след успешно плащане (изисква конфигурация на Stripe webhook).',
    addlPdfDesc: 'Допълнителен капацитет за обработка на PDF страници',
    addlRowsDesc: 'Допълнителен капацитет за обработка на Excel редове',
    oneTimePayment: 'Еднократно плащане',
    purchaseItem: (label: string) => `Закупете ${label}`,
    testPayments: 'Тестови плащания',
    adminOnly: 'Само за администратори',
    testPaymentsDesc: 'Stripe тест-линкове — използвайте карта',
    testPaymentsDesc2: ', произволна бъдеща дата, произволен CVC. Те преминават през същия webhook процес като реалните плащания, за да можете да проверите цялата интеграция.',
    openTestCheckout: 'Отвори тест плащане',
    subscriptionBadge: 'Абонамент',
    addonBadge: 'Добавка',

    // ── Tickets ───────────────────────────────────────────────────────────────
    support: 'Поддръжка',
    supportSubtitle: 'Получете помощ от нашия екип за поддръжка',
    issueSystemNotWorking: 'Системата не работи',
    issueFilesIssues: 'Проблеми с файлове - липсващи файлове, некоректни данни и др.',
    issueGeneralSupport: 'Обща поддръжка',
    issueDowngradeCancel: 'Понижаване/Отмяна на абонамент',
    selectOption: '— Изберете опция —',
    chooseAssistance: 'Моля, изберете с какво имате нужда от помощ',
    description: 'Описание',
    optional: '(по желание)',
    descPlaceholder: 'Опишете проблема си по-подробно...',
    submitting: 'Изпращане...',
    submitRequest: 'Изпращане на заявка',
    requestSubmitted: 'Заявката е изпратена!',
    requestSubmittedDesc: 'Нашият екип за поддръжка ще прегледа заявката ви и ще се свърже с вас скоро.',
    submitAnother: 'Изпратете друга заявка',
    submitFailed: 'Неуспешно изпращане на заявката. Моля, опитайте отново.',

    // ── Users ─────────────────────────────────────────────────────────────────
    usersManagement: 'Управление на потребители',
    createUser: 'Създаване на потребител',
    name: 'Ime',
    role: 'Роля',
    actions: 'Действия',
    noUsersFound: 'Не са намерени потребители',
    loadingUsers: 'Зареждане на потребители...',
    fullName: 'Пълно Ime',
    emailRequired: 'Имейл *',
    passwordRequired: 'Парола *',
    roleRequired: 'Роля *',
    namePlaceholderUser: 'Иван Иванов',
    minChars: 'Минимум 8 символа',
    creating: 'Създаване...',
    removeUser: 'Премахване на потребител',
    removeConfirm: (email: string) => `Премахнете ${email} от тази организация?`,
    removeUserFailed: 'Неуспешно премахване на потребителя',
    createUserFailed: 'Неуспешно създаване на потребителя',
    changePassword: 'Промяна на паролата',
    newPassword: 'Нова парола *',
    savingPassword: 'Запазване...',
    changePasswordFailed: 'Неуспешна промяна на паролата',
    passwordChanged: 'Паролата е сменена успешно',
    tabUsers: 'Потребители',
    tabImport: 'Импорт',
    uploadFile: 'Качи файл',
    uploading: 'Качване...',
    uploadSuccess: 'Файлът е качен успешно',
    uploadFailed: 'Неуспешно качване на файла',
    dragDropFile: 'Провлачете файл тук или кликнете за избор',
    noFileSelected: 'Не е избран файл',
    selectFile: 'Избери файл',
    download: 'Изтегли',
};

type Translations = typeof en;

const translations: Record<Language, Translations> = { en, bg };

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const stored = (localStorage.getItem('language') as Language) || 'en';
    const [language, setLanguageState] = useState<Language>(
        stored === 'bg' ? 'bg' : 'en'
    );

    const setLanguage = (lang: Language) => {
        localStorage.setItem('language', lang);
        setLanguageState(lang);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage(): LanguageContextType {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
    return ctx;
}
